// Problem 2:
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

var EvenFibonnaciSum = function(maxValue) {
  var fib = 1
  var newFib = 2
  var sum = 0
  while (fib < maxValue) {
    if (fib%2 == 0) {
      sum += fib;
    }
    nextFib = fib + newFib;
    fib = newFib;
    newFib = nextFib;
  }
  console.log("Sum is: " + sum);
}

//sum should be 10=(2+8)
EvenFibonnaciSum(10);

//sum should be 44=(2+8+34)
EvenFibonnaciSum(50);

EvenFibonnaciSum(4e6);
